---
title: "Mack Creek Exploration"
format: html
editor: visual
execute:
  warning: false
  message: false
---

```{r}
library(tidyverse)
library(here)
library(janitor)
```

## 1. Read in Mack Creek Vertebrates data

```{r}
mack_verts <- read_csv(here("data", "AS00601.csv"))
```

## 2. A bit of wrangling & exploring

```{r}
verts_clean <- mack_verts %>% clean_names()
```

```{r}
mc_wt_5 <- verts_clean$weight[5]
mc_length_8_20 <- verts_clean$length1[8:20]
mc_dates <- verts_clean$sampledate
```

## 3. Make a salamander subset

```{r}
mc_salamanders <- verts_clean %>%
  filter(species == "DITE")
```

## 4. Make a scatterplot of salamander length x weight

```{r}
salamander_plot <- ggplot(data = mc_salamanders, aes(x = weight, y = length1)) +
  geom_point(color = "coral",
             size = .8,
             alpha = .5) +
  labs(title = "Salamander length vs. weight", 
       x = "Length (mm)", 
       y = "Weight (g)",
       subtitle = "Mack Creek",
       caption = "Gregory, S.V. and I. Arismendi. 2020. Aquatic Vertebrate Population Study in Mack\nCreek, Andrews Experimental Forest, 1987 to present ver 14. Environmental Data Initiative.\n https://doi.org/10.6073/pasta/7c78d662e847cdbe33584add8f809165 (Accessed 2022-08-09).") +
  theme_bw()
salamander_plot
```

```{r}
ggsave(plot = salamander_plot,
       here::here("figs", "salamander_size.png"),
       width = 6,
       height = 5)
```

## 5. Make a cutthroat plot

```{r}
mc_trout <- verts_clean %>%
  filter(species == "ONCL")
```

```{r}
trout_plot <- ggplot(data = mc_trout, aes(x = weight, y = length1)) +
  geom_point(aes(color = reach)) +
  scale_color_manual(values = c("burlywood2", "deepskyblue3", "deeppink4")) +
  facet_wrap(~reach) + 
  labs(title = "Cutthroat trout length vs. weight by creek reach", 
       x = "Length (mm)", 
       y = "Weight (g)") +
  theme_bw()
trout_plot
```

```{r}
ggsave(plot = trout_plot,
       here::here("figs", "cutthroat_size.png"),
       width = 6,
       height = 5)
```
